import numpy as np
# # # # print(np.__version__)
# # # # a=np.array([[[1,2,3],[4,5,6],[6,7,7]]])
# # # # print(a)
# # # # print(a.shape)
# # # # print(a.size)
# # # # print(a.ndim)
# # # # print(a.dtype)
# # # # b=np.zeros((3,5))
# # # # print(b)
# # # # c=np.ones((3,5))
# # # # print(c)
# # # # d=np.arange(0,30,2)
# # # # print(d)
# # # # e=np.linspace(0,1,5)
# # # # print(e)
# # # # f=np.eye(3)
# # # # print(f)
# # # # np.random.random((2,3))
# # # # np.random.randint(1,10,(2,3))
# # # a=np.array([[1,2,3],[4,5,6],[7,8,9]])
# # # print(a[1,:])
# # # print(a[:,1])
# # # arr=np.array([10,20,30,40,50])
# # # print(arr[arr>25])
# # # a=np.array([10,20,30])
# # # b=np.array([10,20,30])
# # # # print(a+b)
# # # a=np.array([[1,2,3],[4,5,6]])
# # # b=np.array([[1,2,3],[4,5,6]])
# # # print(a+b)
# # b=np.array([10,20,30,40,50])
# # print(np.sum(b))
# # print(np.mean(b))
# # print(np.std(b))
# # print(np.var(b))
# # print(np.min(b))
# # print(np.max(b))
# # print(np.argmax(b))
# # print(np.argmin(b))
# # a=np.arange(10)
# # b=a.reshape(5,2)
# # # print(b)
# # a=np.array([1,2,3,4,5,6,7,7,7])
# # b=np.array([1,2,3,4,5,6,7,9,8])
# # print(a.flatten())
# # print(np.split(a,3))
# # print(np.concatenate((a,b)))

# # a=np.array([[1,2,3],[5,6,7],[8,7,9]])
# # b=np.array([[1,2,3],[5,6,7],[8,7,9]])
# # print(np.matmul(a,b))
# a=np.array([1,2,3])
# b=np.array([4,5,6])
# print(np.dot(a,b))
# a=np.array([[1,2,3],[4,5,6]])
print(np.random.rand(4))
rng1=np.random.default_rng(seed=5)
print(rng1)